# Generated by Django 4.2.2 on 2023-06-28 02:43

import cavityquest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=11)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('number_of_records', models.IntegerField()),
                ('doctors_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(blank=True, default=None, null=True, upload_to=cavityquest.models.content_file_name)),
                ('date_created', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cavityquest.patient')),
            ],
        ),
    ]
