# Generated by Django 4.2.2 on 2023-08-17 08:20

import cavityquest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(max_length=120, null=True)),
                ('contact_number', models.CharField(max_length=11, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('doctors_note', models.TextField(blank=True, null=True)),
                ('treatment', models.CharField(choices=[('Dental Braces', 'Dental Braces'), ('Crown', 'Crown'), ('Veneers', 'Veneers'), ('Partial Denture', 'Partial Denture'), ('Full Denture', 'Full Denture'), ('Wisdom Tooth Surgery', 'Wisdom Tooth Surgery')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to=cavityquest.models.content_file_name)),
                ('date_created', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_uploads', to='cavityquest.patient')),
            ],
        ),
    ]
