# Generated by Django 4.2.2 on 2023-08-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Dental Braces', 'Dental Braces'), ('Tooth Extraction', 'Tooth Extraction'), ('Crown', 'Crown'), ('Veneers', 'Veneers'), ('Partial Denture', 'Partial Denture'), ('Full Denture', 'Full Denture'), ('Wisdom Tooth Surgery', 'Wisdom Tooth Surgery')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='treatment',
        ),
        migrations.AddField(
            model_name='patient',
            name='treatments',
            field=models.ManyToManyField(to='cavityquest.treatmentoption'),
        ),
    ]
