# Generated by Django 4.2.2 on 2023-08-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clinic', to='cavityquest.clinic'),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='clinic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clinic', to='cavityquest.clinic'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dentists',
            field=models.ManyToManyField(blank=True, default=None, related_name='dentists', to='cavityquest.dentist'),
        ),
    ]
