# Generated by Django 4.2.2 on 2023-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0002_patient_clinic_alter_dentist_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatments',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
