# Generated by Django 4.2.2 on 2023-08-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0002_treatmentoption_remove_patient_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='treatments',
        ),
        migrations.DeleteModel(
            name='TreatmentOption',
        ),
        migrations.AddField(
            model_name='patient',
            name='treatments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
