# Generated by Django 4.2.2 on 2023-08-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0003_alter_patient_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
