# Generated by Django 4.2.2 on 2023-06-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0003_alter_patient_address_alter_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='number_of_records',
        ),
    ]
