# Generated by Django 4.2.2 on 2023-08-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0003_remove_patient_treatments_delete_treatmentoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatments',
            field=models.JSONField(blank=True),
        ),
    ]
