# Generated by Django 4.2.2 on 2023-08-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0004_alter_patient_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
