# Generated by Django 4.2.2 on 2023-08-26 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0004_alter_patient_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clinic', to='cavityquest.clinic'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_clinic', to='cavityquest.clinic'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dentists',
            field=models.ManyToManyField(related_name='dentists', to='cavityquest.dentist'),
        ),
    ]
