# Generated by Django 4.2.2 on 2023-06-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='url',
            new_name='image',
        ),
    ]
