# Generated by Django 4.2.2 on 2023-08-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0005_alter_dentist_clinic_alter_patient_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dentists',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='dentists', to='cavityquest.dentist'),
        ),
    ]
