# Generated by Django 4.2.2 on 2023-08-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0006_alter_patient_dentists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dentists',
        ),
        migrations.AddField(
            model_name='patient',
            name='dentists',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dentists', to='cavityquest.dentist'),
        ),
    ]
