# Generated by Django 4.2.2 on 2023-06-30 02:23

import cavityquest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0006_rename_url_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=cavityquest.models.content_file_name),
        ),
    ]
