# Generated by Django 4.2.2 on 2023-08-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0007_remove_patient_dentists_patient_dentists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='dentists',
            new_name='dentist',
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
