# Generated by Django 4.2.2 on 2023-08-19 04:50

import cavityquest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0008_alter_patient_address_alter_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=cavityquest.models.content_file_name),
        ),
    ]
