# Generated by Django 4.2.2 on 2023-08-27 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0008_rename_dentists_patient_dentist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dentist', to='cavityquest.dentist'),
        ),
    ]
