# Generated by Django 4.2.2 on 2023-08-19 04:59

import cavityquest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0011_alter_imageupload_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(default=None, upload_to=cavityquest.models.content_file_name),
        ),
    ]
