# Generated by Django 4.2.2 on 2023-08-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavityquest', '0014_alter_imageupload_image_alter_imageupload_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='treatments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
